language: python

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      compiler: gcc
      services:
        - docker

script:
  - python bbox.py pull
  - python bbox.py build
